### ISSUE TITLE
Reproducing issue

### ISSUE THREAD

**Issue by ahyungshin** [lslrh/CPSL#10]
Hello. First, I want to thank you for this code. It helped me a lot.

I’ve been reproducing the results on my own, using four A5000 gpus. 

At phase one, the performance was just the same which is 55.6 mIoU as you wrote in the readme file. However, I think there are some issues at phase two since the performance has dropped to 58.2, 1 mIoU lower compared to your work. I’m not clear whether the cause of the issue is me or not. 

So if there is someone who tried reproducing this work and been through this issue, please help me.

 I will be appreciated so much. Thank you.

**Comment by lslrh** [comment]
Thanks for your interest. I find the reason is that the last version does not load the self-supervised pre-trained model (SimCLR), but it loads the ImageNet pre-trained model. I have corrected this. Please try again. I think it will work.
