### ISSUE TITLE
关于 from_gta5_to_cityscapes_on_deeplabv2_best_model.pkl 模型文件

### ISSUE THREAD

**Issue by qubewx** [lslrh/CPSL#11]
请问这个模型文件是用 源域+源域标签 用DeepLab有监督训练得到的吗

**Comment by lslrh** [comment]
> 请问这个模型文件是用 源域+源域标签 用DeepLab有监督训练得到的吗

这个模型是用AdaptSeg[1]做了初始化之后得到的，初始化之后的性能大约为41.4mIoU.

[1] Yi-Hsuan Tsai, Wei-Chih Hung, Samuel Schulter, Kihyuk Sohn, Ming-Hsuan Yang, and Manmohan Chandraker.
Learning to adapt structured output space for semantic segmentation, CVPR 2018.

**Comment by qubewx** [comment]
好的谢谢，我想试一下用其他的数据集效果怎么样。那我要先在AdaptSeg上训练一个初始化模型，再执行您的Stage1、2、3对吗

**Comment by lslrh** [comment]
> 好的谢谢，我想试一下用其他的数据集效果怎么样。那我要先在AdaptSeg上训练一个初始化模型，再执行您的Stage1、2、3对吗

对的，是这样的；也可以用source-only做初始化，只是性能可能会下降。

**Comment by qubewx** [comment]
prototypes_on_cityscapes_from_deeplabv2&nbsp;&nbsp; 请问这个模型文件是干嘛用的，stage1&nbsp;&nbsp; train的时候加载不进来，而且它的大小只有6.9K，是我哪里搞错了吗。感谢您的回复，对我帮助很大！
&nbsp;
------------------

正方形
***@***.***



&nbsp;




------------------&nbsp;Original message&nbsp;------------------
From: "Ruihuang Li"; 
Sendtime: Sunday, Dec 11, 2022 11:23 AM
To: "lslrh/CPSL"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [lslrh/CPSL] 关于 from_gta5_to_cityscapes_on_deeplabv2_best_model.pkl 模型文件 (Issue #11)





  
好的谢谢，我想试一下用其他的数据集效果怎么样。那我要先在AdaptSeg上训练一个初始化模型，再执行您的Stage1、2、3对吗
  
对的，是这样的；也可以用source-only做初始化，只是性能可能会下降。

**Comment by lslrh** [comment]
> 

这个不是模型文件，是prototype的初始化。加载不进来有报错吗？

**Comment by qubewx** [comment]
我看了一下，因为我换了数据集，数组增强那块报错了。我想把您提到的那个即插即用的CPSL模块拿出来，用到其他的UDA框架试试。不知道代码上如何操作。谢谢！


------------------

正方形
***@***.***



&nbsp;





------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Ruihuang ***@***.***&gt;;
Send time:&nbsp;Monday, Dec 12, 2022 7:29 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [lslrh/CPSL] 关于 from_gta5_to_cityscapes_on_deeplabv2_best_model.pkl 模型文件 (Issue #11)





   
这个不是模型文件，是prototype的初始化。加载不进来有报错吗？

**Comment by lslrh** [comment]
> 
如果换数据集，那prototypes文件是要自己生成的，我代码里有提供生成并保存prototype的代码。另外数据增广报错的话，可能要修改dataloader.

**Comment by qubewx** [comment]
我想把CPSL模块单独拿出来，用在其他UDA框架，代码该怎么操作呢


------------------

正方形
***@***.***



&nbsp;





------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Ruihuang ***@***.***&gt;;
Send time:&nbsp;Tuesday, Dec 13, 2022 2:10 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [lslrh/CPSL] 关于 from_gta5_to_cityscapes_on_deeplabv2_best_model.pkl 模型文件 (Issue #11)





   
如果换数据集，那prototypes文件是要自己生成的，我代码里有提供生成并保存prototype的代码。另外数据增广报错的话，可能要修改dataloader.
