### ISSUE TITLE
About the parameter 'resume_path' in the soft pseudo label generation of Stage3

### ISSUE THREAD

**Issue by PhDCJojo** [lslrh/CPSL#3]
@lslrh Thank you for opening source code.
Why you chose the weight parameter of the best model of Stage1  to generate soft pseudo label of Stage3 rather than use the weight parameter of the best model of Stage2?

- Stage3 Generate soft pseudo label.
python generate_pseudo_label.py --name gta2citylabv2_stage2 --flip \
--resume_path ./logs/gta2citylabv2_stage1Denoise/from_gta5_to_cityscapes_on_deeplabv2_best_model.pkl --no_droplast\
--bn_clr --student_init simclr

**Comment by lslrh** [comment]
> @lslrh Thank you for opening source code. Why you chose the weight parameter of the best model of Stage1 to generate soft pseudo label of Stage3 rather than use the weight parameter of the best model of Stage2?
> 
> * Stage3 Generate soft pseudo label.
>   python generate_pseudo_label.py --name gta2citylabv2_stage2 --flip 
>   --resume_path ./logs/gta2citylabv2_stage1Denoise/from_gta5_to_cityscapes_on_deeplabv2_best_model.pkl --no_droplast
>   --bn_clr --student_init simclr

Thanks for your remind. I have rectified it. The stage2 model should be used here.
