### ISSUE TITLE
The model from synthia to cityscapes

### ISSUE THREAD

**Issue by ywher** [lslrh/CPSL#4]
Hi, nice work. 
I wonder if you can share the models adapted from SYNTHIA to Cityscapes?
I would appreciate it if you could share them with us.

**Comment by lslrh** [comment]
Thanks for your interest. The attached are the training logs of different stages. 

[run_2021_06_19_14_28_11.log](https://github.com/lslrh/CPSL/files/9228014/run_2021_06_19_14_28_11.log)
[run_2021_06_24_23_01_12.log](https://github.com/lslrh/CPSL/files/9228015/run_2021_06_24_23_01_12.log)
