### ISSUE TITLE
question with cutmix augmentation

### ISSUE THREAD

**Issue by ksh11023** [lslrh/CPSL#8]
Hello, I'm very interested with your amazing work.

I rerun your code, but the ‘cutmix’ augmentation in the stage1 phase does not seem to work properly.
Below is the visualization result of input image (target_x), prediction (target_out[‘out’]), and pseudo gt (threshold_arg) in order, all of which are applied to ‘cutmix’ augmentation.
In my opinion, it seems to be a problem caused by the difference between the label size and the input size in the process of augmentation of target PGT.
Let me know if I’ve misunderstood anything.

Thank you very much. 

<img width="747" alt="스크린샷 2022-09-15 오후 3 29 33" src="https://user-images.githubusercontent.com/50094436/190330679-435cc4ea-f032-4bb1-9884-9cea3f466c4a.png">

<img width="738" alt="스크린샷 2022-09-15 오후 1 17 16" src="https://user-images.githubusercontent.com/50094436/190313127-6e093d12-1801-40a1-9738-b6ef92c24c62.png">

<img width="747" alt="스크린샷 2022-09-15 오후 1 17 26" src="https://user-images.githubusercontent.com/50094436/190313186-2937e10e-1382-40c8-a826-8836f68699c3.png">

**Comment by lslrh** [comment]
Thanks for your very kind remind. I am sorry for making such a mistake. I have corrected it.

**Comment by LL0617** [comment]
您好，请问你重新跑的结果出来了吗？我跑出的最高精度stage1只有54.92
此外，请问您有没有试过不采用cutmix的精度大致是多少？
感谢您的回复
