### ISSUE TITLE
Can two 3090 GPU reproduce the performance

### ISSUE THREAD

**Issue by yuheyuan** [lslrh/CPSL#9]
One 3090GPU have 24GB. ProDA and your code write "to reproduce the performance, you need 4 GPUs with no less than 16G memory."
So I want to know if it can use two GPU reproduce the performance.

**Comment by lslrh** [comment]
Sorry, I worry that two 3090 could not meet the requirement of batch size 4. It could only support batch size 2, which may influence the result.

**Comment by yuheyuan** [comment]
> Sorry, I worry that two 3090 could not meet the requirement of batch size 4. It could only support batch size 2, which may influence the result.


oh,thank you. I know.
In other words, set batch size 2, then I can run the code and go through the all process.
keep batch size 4. the result that I can't run the code because out of GPU memory limits.
